### ISSUE TITLE
I couldn't set it up.

### ISSUE THREAD

**Issue by snowy1000** [Androz2091/ManageInvite#29]
Hello Androz!

For a while I'm trying to set this bot up but I couldn't. Here are some questions: 

- I get `Error: connect ECONNREFUSED 127.0.0.1:5432` error and I don't know why. 
- I added `mydomain.com/login` to oAuth2 on Discord Developers but still getting Invalid oAuth redirect_uri error.
- ```js
    database: {
        user: "",
        host: "localhost",
        database: "manage_invite",
        password: "",
        port: 5432
    }```
I couldn't figure out what to write to places above.-config.js-

- ```js
    mongodb:        "XXXXXXXXXXX",
    discord:        "XXXXXXXXXXX",
```
What should I write here -config.js-

**Comment by Androz2091** [comment]
Hello,
Yes, currently the bot is very difficult to install - there is no script to prepare the PostgreSQL database.
`mongo` is your MongoDB URL.
`discord` is a link to your discord server.
`mydomain.com/login` must be `mydomain.com/callback`.

**Comment by LeomanPlay** [comment]
Hello, I am getting same error:
`PS C:\Users\Leoma\Desktop\ManageInvite-master> node sharder.js
Hello, Leoma. Thanks for using ManageInvite.
[2020-05-21 10:51:14.808]: LOG Shard #0 has started.
[2020-05-21 10:51:15.588]: LOG Top.gg stats successfully posted.
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
[2020-05-21 10:51:25.400]: LOG Shard #1 has started.
[2020-05-21 10:51:25.858]: LOG Top.gg stats successfully posted.
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
PS C:\Users\Leoma\Desktop\ManageInvite-master>`
Is it because of mongo?
