### ISSUE TITLE
i'm getting error: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by ultrait165** [Androz2091/ManageInvite#44]
this is my log

Error: Connection terminated unexpectedly
    at Connection.con.once (/home/aphrodite/node_modules/pg/lib/client.js:275:71)
    at Object.onceWrapper (events.js:277:13)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/home/aphrodite/node_modules/pg/lib/connection.js:126:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: Connection terminated unexpectedly
    at Connection.con.once (/home/aphrodite/node_modules/pg/lib/client.js:275:71)
    at Object.onceWrapper (events.js:277:13)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/home/aphrodite/node_modules/pg/lib/connection.js:126:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Androz2091** [comment]
Looks like it's because your PostgreSQL server has stopped...

**Comment by ultrait165** [comment]
i'm sure i did everything correctly i've tried it on a vps and on localhost, with external mongo and internal and localhost everything

**Comment by Androz2091** [comment]
Yes, but here the problem is with `PostgreSQL` not mongo.

**Comment by ultrait165** [comment]
okay can u tell me about any fix? sorry for interrupt you

**Comment by Androz2091** [comment]
You need to keep your PostgreSQL server online...

**Comment by ultrait165** [comment]
now i'm getting this error 
![image](https://user-images.githubusercontent.com/65005649/82727892-8e7d9b00-9ced-11ea-9193-658c219bce06.png)
