### ISSUE TITLE
i'm getting error

### ISSUE THREAD

**Issue by GabrielSSQ** [Androz2091/ManageInvite#49]
my error: { error: relation "guilds" does not exist
    at Parser.parseErrorMessage (/rbd/pnpm-volume/ce75963e-f540-409d-a3a3-cf25e4c1ac71/node_modules/.registry.npmjs.org/pg-protocol/1.2.3/node_modules/pg-protocol/dist/parser.js:241:15)
    at Parser.handlePacket (/rbd/pnpm-volume/ce75963e-f540-409d-a3a3-cf25e4c1ac71/node_modules/.registry.npmjs.org/pg-protocol/1.2.3/node_modules/pg-protocol/dist/parser.js:89:29)
    at Parser.parse (/rbd/pnpm-volume/ce75963e-f540-409d-a3a3-cf25e4c1ac71/node_modules/.registry.npmjs.org/pg-protocol/1.2.3/node_modules/pg-protocol/dist/parser.js:41:38)
    at Socket.stream.on (/rbd/pnpm-volume/ce75963e-f540-409d-a3a3-cf25e4c1ac71/node_modules/.registry.npmjs.org/pg-protocol/1.2.3/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  length: 105,
  name: 'error',
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '32',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable' }

**Comment by Androz2091** [comment]
Yes, currently it's not possible to initialize the database. A SQL script will be published in some days.

**Comment by GabrielSSQ** [comment]
Ah Okay im waiting

**Comment by ultrait165** [comment]
i'm getting the same error what should i do

**Comment by a4arpan** [comment]
+1 waiting for SQL script
