### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sysysysy242** [Androz2091/ManageInvite#74]
Hi, i configured my manager invite but i launche that and i have : 

D:\Bureau\discord\managerinvite\ManageInvite\helpers\database.js:341
                        joinData: membersJoinData.find((memberJoinDataObj) => `${memberJoinDataObj.user_id}${memberJoinDataObj.guild_id}` === `${memberID.userID}${memberID.guildID}`)?.member_join_data_agg || null,
                                                                                                                                                                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Bureau\discord\managerinvite\ManageInvite\structures\Client.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
(node:13780) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (D:\Bureau\discord\managerinvite\ManageInvite\node_modules\discord.js\src\sharding\Shard.js:155:16)
    at Object.onceWrapper (events.js:417:26)
    at Shard.emit (events.js:310:20)
    at Shard._handleExit (D:\Bureau\discord\managerinvite\ManageInvite\node_modules\discord.js\src\sharding\Shard.js:371:10)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:13780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
D:\Bureau\discord\managerinvite\ManageInvite\helpers\database.js:341
                        joinData: membersJoinData.find((memberJoinDataObj) => `${memberJoinDataObj.user_id}${memberJoinDataObj.guild_id}` === `${memberID.userID}${memberID.guildID}`)?.member_join_data_agg || null,

**Comment by Androz2091** [comment]
Hello, this is because you must install Node.js v14
